[BD] Add compatibility to call log_request_fail in python3 (#317)
Related to https://openedx.atlassian.net/browse/BOM-1359

Currently (analytics_data_api.v0.tests.test_connections.BotoHttpConnectionTests) tests are failing when they call self.log_request_fail(method, url, body, duration, response.status) with a AttributeError: 'str' object has no attribute 'decode' in
https://github.com/elastic/elasticsearch-py/blob/1.9.0/elasticsearch/connection/base.py#L88

It seems that it was added a try catch block for that in the latest versions of elasticsearch-py but the readme for the 2.x version says that For Elasticsearch 1.0 and later, use the major version 1 (1.x.y) of the library https://github.com/elastic/elasticsearch-py/tree/2.x

I also moved the constraints of elasticsearch-dsl to constraints.txt

This is one of the errors that we have currently in the python3 version (see tests in https://github.com/eduNEXT/edx-analytics-data-api/pull/1)